repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: ".*(data.*|extern.*|licenses.*|_parsetab.py)$"
  - id: trailing-whitespace
    exclude: ".*(data.*|extern.*|licenses.*|_parsetab.py|test_cds.py)$"
# - repo: https://github.com/timothycrosley/isort
#   rev: 5.9.2
#   hooks:
#   - id: isort
# - repo: https://github.com/asottile/pyupgrade
#   rev: v2.21.0
#   hooks:
#     - id: pyupgrade
- repo: local
  hooks:
    - id: tox-codestyle
      name: check codestyle (flake8)
      entry: tox -e codestyle
      language: system
      pass_filenames: false
- repo: local
  hooks:
    - id: changelogs-rst
      name: changelog filenames
      language: fail
      entry: >-
        changelog files must be named <sub-package>/####.(bugfix|feature|api).rst
        or ####.other.rst (in the root directory only)
      exclude: >-
        ^docs/changes/[\w\.]+/(\d+\.(bugfix|feature|api)(\.\d)?.rst|.gitkeep)
      files: ^docs/changes/[\w\.]+/
    - id: changelogs-rst-other
      name: changelog filenames for other category
      language: fail
      entry: >-
        only "other" changelog files must be placed in the root directory
      exclude: >-
        ^docs/changes/(\d+\.other.rst|README.rst|template.rst)
      files: ^docs/changes/\d+.\w+.rst
