comment: off
coverage:
  status:
    project:
      default:
        target: auto
        # adjust accordingly based on how flaky your tests are
        # this allows a 0.02% drop from the previous base commit coverage
        threshold: 0.02%
