version: 2.1

jobs:
  figure:
    parameters:
      jobname:
        type: string
    docker:
      - image: circleci/python:3.9
    environment:
      TOXENV=<< parameters.jobname >>
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
              sudo apt update
              sudo apt install texlive texlive-latex-extra texlive-fonts-recommended dvipng cm-super
              pip install pip tox --upgrade
      - run:
          name: Run tests
          command: tox -v -- -W ignore:np.asscalar -W ignore::DeprecationWarning -k "not test_no_numpy_warnings"
      - store_artifacts:
          path: results
      - run:
          name: "Image comparison page is available at: "
          command: echo "${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/results/fig_comparison.html"

  deploy-reference-images:
    parameters:
      jobname:
        type: string
    docker:
      - image: circleci/python:3.9
    environment:
      TOXENV: << parameters.jobname >>
      GIT_SSH_COMMAND: ssh -i ~/.ssh/id_rsa_bfaaefe38d95110b75c79252bafbe0fc
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
              sudo apt update
              sudo apt install texlive texlive-latex-extra texlive-fonts-recommended dvipng cm-super
              pip install pip tox --upgrade
      # Clear out all the ssh keys so that it always uses the write deploy key
      - run: ssh-add -D
      # Add private key for deploying to the figure tests repo
      - add_ssh_keys:
          fingerprints: "	bf:aa:ef:e3:8d:95:11:0b:75:c7:92:52:ba:fb:e0:fc"
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: git config --global user.email "astropy@circleci" && git config --global user.name "Astropy Circle CI"
      - run: git clone git@github.com:astropy/astropy-figure-tests.git --depth 1 -b astropy-${CIRCLE_BRANCH} ~/astropy-figure-tests/
      # Generate Reference images
      - run:
          name: Generate reference images
          command: tox -v -- --mpl-generate-path=/home/circleci/astropy-figure-tests/figures/$TOXENV -W ignore:np.asscalar -W ignore::DeprecationWarning -k "not test_no_numpy_warnings"
      - run: |
          cd ~/astropy-figure-tests/
          git pull
          git status
          git add .
          git commit -m "Update reference figures from ${CIRCLE_BRANCH}" || echo "No changes to reference images to deploy"
          git push

workflows:
  version: 2

  figure-tests:
    jobs:
      - figure:
          name: << matrix.jobname >>
          matrix:
            parameters:
              jobname:
                - "py39-test-image-mpl311"
                - "py39-test-image-mpldev"

      - deploy-reference-images:
          name: baseline-<< matrix.jobname >>
          matrix:
            parameters:
              jobname:
                - "py39-test-image-mpl311"
                - "py39-test-image-mpldev"
          requires:
            - << matrix.jobname >>
          filters:
            branches:
              only:
                - main

notify:
  webhooks:
    - url: https://giles.cadair.dev/circleci
